"""Offline, experimental sign-to-road hypothesis simulator; never imported by an app.

This deliberately assumes a synthetic or reviewed geometry hint. It does NOT
implement a lane/sign-position estimator, establish its accuracy, confirm a
recognition, or change the shared speed-reference state machine. Outcomes refer
only to one candidate: ego = associated with the current corridor, reject =
associated with a different corridor, hold = unresolved. None guarantees a live
display event. The numerical limits below are experimental test parameters.
"""
from __future__ import annotations

from dataclasses import dataclass, field
import math


@dataclass(frozen=True)
class Encounter:
    session_id: str
    traversal_id: str
    branch_id: str
    bundle_id: str = "synthetic-bundle"
    camera_geometry_id: str = "synthetic-mount"


@dataclass(frozen=True)
class Pose:
    captured_at_ms: int
    way_id: str
    stable: bool = True
    horizontal_accuracy_m: float = 5.0
    course_accuracy_deg: float = 5.0


@dataclass(frozen=True)
class GeometryHint:
    # An oracle input for testing decision wiring, NOT a learned feature or truth
    # generated by this simulator. Real model evaluation must measure it separately.
    sign_corridor: str  # mainline, branch, or unknown
    source: str = "synthetic"
    branch_kind: str = "exit"  # exit, service_area, or junction (offline only)
    mainline_way_ids: tuple[str, ...] = ("motorway-1", "motorway-2")
    branch_way_ids: tuple[str, ...] = ("ramp-1",)
    topology_built_at_ms: int = 0
    topology_usable: bool = True
    inside_directed_interval: bool = True


@dataclass(frozen=True)
class SpeedSample:
    captured_at_ms: int
    speed_kmh: float


@dataclass(frozen=True)
class Observation:
    encounter: Encounter
    frame_id: str
    captured_at_ms: int
    physical_track_id: str
    speed_limit_kmh: int
    pose: Pose | None
    geometry: GeometryHint | None
    image_center_x: float = 0.75  # Kept for ablations; never a blanket mask.
    status: str = "analyzed"


@dataclass(frozen=True)
class Decision:
    outcome: str
    reason: str
    corroboration: tuple[str, ...] = ()
    distinct_observations_in_burst: int = 0


@dataclass
class _Track:
    first_at_ms: int
    last_at_ms: int
    values: set[int] = field(default_factory=set)
    burst_count: int = 0


@dataclass
class _EncounterState:
    first_at_ms: int | None = None
    last_at_ms: int | None = None
    frames: dict[str, tuple[int, set[str], tuple]] = field(default_factory=dict)
    tracks: dict[str, _Track] = field(default_factory=dict)
    dismissed_at_ms: int | None = None
    entered_branch: bool = False
    expired: bool = False


class ExitHypothesisSimulation:
    """Deterministic experimental wiring, with no fitted scores or live effects."""

    def __init__(self, *, max_pose_age_ms: int = 1_500,
                 max_observation_gap_ms: int = 2_500,
                 sequence_window_ms: int = 15_000,
                 max_encounter_gap_ms: int = 15_000,
                 max_encounter_duration_ms: int = 60_000):
        for value in (max_pose_age_ms, max_observation_gap_ms, sequence_window_ms,
                      max_encounter_gap_ms, max_encounter_duration_ms):
            if type(value) is not int or not 1 <= value <= 60_000:
                raise ValueError("Experimental windows must be integer milliseconds in 1..60000")
        self.max_pose_age_ms = max_pose_age_ms
        self.max_observation_gap_ms = max_observation_gap_ms
        self.sequence_window_ms = sequence_window_ms
        self.max_encounter_gap_ms = max_encounter_gap_ms
        self.max_encounter_duration_ms = max_encounter_duration_ms
        self._states: dict[Encounter, _EncounterState] = {}

    def _state(self, encounter: Encounter) -> _EncounterState:
        # Offline simulations retain at most 32 encounters, in insertion order.
        # A new traversal must use a new identity; evicted history is not reusable.
        if encounter not in self._states:
            if len(self._states) == 32:
                del self._states[next(iter(self._states))]
            self._states[encounter] = _EncounterState()
        return self._states[encounter]

    def dismiss(self, encounter: Encounter, at_ms: int) -> None:
        """Record a review cue scoped to this branch encounter; it grants no veto."""
        self._validate_encounter(encounter)
        self._validate_time(at_ms)
        state = self._state(encounter)
        previous = [x for x in (state.last_at_ms, state.dismissed_at_ms) if x is not None]
        if previous and at_ms < max(previous):
            raise ValueError("Dismissal cannot precede already observed evidence")
        if state.expired or state.entered_branch:
            return
        state.dismissed_at_ms = at_ms

    def observe(self, observation: Observation,
                speed_history: tuple[SpeedSample, ...] = ()) -> Decision:
        o = observation
        self._validate(o, speed_history)
        state = self._state(o.encounter)
        if state.dismissed_at_ms is not None and state.dismissed_at_ms > o.captured_at_ms:
            raise ValueError("Future dismissal would leak into an earlier observation")
        if o.status != "analyzed":
            return Decision("hold", "frame_not_analyzed")
        expired = ((state.last_at_ms is not None
                    and o.captured_at_ms - state.last_at_ms > self.max_encounter_gap_ms)
                   or (state.first_at_ms is not None
                       and o.captured_at_ms - state.first_at_ms > self.max_encounter_duration_ms))
        if expired or state.expired:
            state.expired = True
            state.frames.clear()
            state.tracks.clear()
            state.dismissed_at_ms = None
            return Decision("hold", "encounter_expired")
        frame = state.frames.get(o.frame_id)
        g = o.geometry
        frame_context = (o.pose, None if g is None else (
            g.source, g.branch_kind, g.mainline_way_ids, g.branch_way_ids,
            g.topology_built_at_ms, g.topology_usable, g.inside_directed_interval))
        if frame is not None:
            if frame[0] != o.captured_at_ms:
                raise ValueError("One immutable frame cannot have two capture times")
            if frame[2] != frame_context:
                raise ValueError("One immutable frame cannot have contradictory road context")
            if o.physical_track_id in frame[1]:
                return Decision("hold", "duplicate_frame")
            if o.captured_at_ms != state.last_at_ms:
                return Decision("hold", "non_increasing_capture_time")
        elif state.last_at_ms is not None and o.captured_at_ms <= state.last_at_ms:
            return Decision("hold", "non_increasing_capture_time")
        if len(state.frames) >= 256 or len(state.tracks) >= 64:
            state.expired = True
            state.frames.clear()
            state.tracks.clear()
            state.dismissed_at_ms = None
            return Decision("hold", "encounter_capacity_exceeded")
        # Multiple candidates from the same frame are allowed, exactly once each.
        state.frames.setdefault(o.frame_id, (o.captured_at_ms, set(), frame_context))[1].add(o.physical_track_id)
        if state.first_at_ms is None:
            state.first_at_ms = o.captured_at_ms
        state.last_at_ms = o.captured_at_ms
        track = state.tracks.setdefault(
            o.physical_track_id, _Track(o.captured_at_ms, o.captured_at_ms))
        gap = o.captured_at_ms - track.last_at_ms
        if gap > self.max_observation_gap_ms:
            track.values.clear()
            track.first_at_ms = o.captured_at_ms
        track.burst_count = (track.burst_count + 1
                             if gap <= self.max_observation_gap_ms else 1)
        track.last_at_ms = o.captured_at_ms
        track.values.add(o.speed_limit_kmh)
        support = self._corroboration(o, state, speed_history)

        def result(outcome: str, reason: str) -> Decision:
            return Decision(outcome, reason, support, track.burst_count)

        if o.pose is None:
            state.dismissed_at_ms = None
            support = tuple(s for s in support if s != "dismissed_in_encounter")
            return result("hold", "missing_pose")
        if o.captured_at_ms - o.pose.captured_at_ms > self.max_pose_age_ms:
            state.dismissed_at_ms = None
            support = tuple(s for s in support if s != "dismissed_in_encounter")
            return result("hold", "stale_pose")
        if (not o.pose.stable or o.pose.horizontal_accuracy_m > 20
                or o.pose.course_accuracy_deg > 25):
            state.dismissed_at_ms = None
            support = tuple(s for s in support if s != "dismissed_in_encounter")
            return result("hold", "unreliable_pose")
        g = o.geometry
        if g is None or not g.topology_usable:
            return result("hold", "missing_geometry")
        if o.pose.way_id in g.branch_way_ids:
            state.entered_branch = True
            # Ramp entry releases the mainline encounter's dismissal context.
            state.dismissed_at_ms = None
            support = tuple(s for s in support if s != "dismissed_in_encounter")
            if g.sign_corridor == "branch":
                return result("ego", "sign_on_entered_branch")
            return result("hold", "branch_entered_other_sign_unresolved")
        if state.entered_branch:
            # Reusing this traversal after entry must not reinstate an old veto.
            return result("hold", "mainline_encounter_ended")
        if o.pose.way_id not in g.mainline_way_ids or not g.inside_directed_interval:
            return result("hold", "outside_mainline_encounter")
        if g.sign_corridor == "mainline":
            return result("ego", "sign_on_current_mainline")
        if g.sign_corridor == "branch":
            return result("reject", "sign_on_other_corridor")
        return result("hold", "sign_corridor_unresolved")

    @staticmethod
    def _validate_time(value: int) -> None:
        if type(value) is not int or value < 0:
            raise ValueError("Timestamps must be nonnegative integer milliseconds")

    @staticmethod
    def _validate_encounter(encounter: Encounter) -> None:
        for identity in (encounter.session_id, encounter.traversal_id, encounter.branch_id,
                         encounter.bundle_id, encounter.camera_geometry_id):
            if not isinstance(identity, str) or not identity.strip():
                raise ValueError("Every encounter identity must be nonempty")

    @staticmethod
    def _validate(o: Observation, speeds: tuple[SpeedSample, ...]) -> None:
        ExitHypothesisSimulation._validate_encounter(o.encounter)
        ExitHypothesisSimulation._validate_time(o.captured_at_ms)
        if not o.frame_id or not o.physical_track_id:
            raise ValueError("Frame and physical-track identity are required")
        if o.status not in {"analyzed", "skipped", "failed", "interrupted"}:
            raise ValueError("Unknown frame status")
        if not math.isfinite(o.image_center_x) or not 0 <= o.image_center_x <= 1:
            raise ValueError("Image centre must be normalized")
        if o.pose:
            ExitHypothesisSimulation._validate_time(o.pose.captured_at_ms)
            if o.pose.captured_at_ms > o.captured_at_ms:
                raise ValueError("Future pose would leak into an earlier observation")
            if any(not math.isfinite(x) or x < 0 for x in
                   (o.pose.horizontal_accuracy_m, o.pose.course_accuracy_deg)):
                raise ValueError("Pose accuracy must be finite and nonnegative")
        if o.geometry:
            g = o.geometry
            ExitHypothesisSimulation._validate_time(g.topology_built_at_ms)
            if g.source not in {"synthetic", "reviewed_geometry"}:
                raise ValueError("Geometry must be explicitly synthetic or reviewed")
            if g.sign_corridor not in {"mainline", "branch", "unknown"}:
                raise ValueError("Unknown corridor hint")
            if g.branch_kind not in {"exit", "service_area", "junction"}:
                raise ValueError("Unknown branch kind")
            if set(g.mainline_way_ids) & set(g.branch_way_ids):
                raise ValueError("Mainline and branch corridors must be distinct")
            if g.topology_built_at_ms > o.captured_at_ms:
                raise ValueError("Future topology is not an as-driven input")
        previous = None
        for s in speeds:
            ExitHypothesisSimulation._validate_time(s.captured_at_ms)
            if s.captured_at_ms > o.captured_at_ms:
                raise ValueError("Future speed would leak into an earlier observation")
            if previous is not None and s.captured_at_ms <= previous:
                raise ValueError("Speed sample timestamps must strictly increase")
            if not math.isfinite(s.speed_kmh) or s.speed_kmh < 0:
                raise ValueError("Speed must be finite and nonnegative")
            previous = s.captured_at_ms

    def _corroboration(self, o: Observation, state: _EncounterState,
                       speeds: tuple[SpeedSample, ...]) -> tuple[str, ...]:
        result = []
        recent = [s for s in speeds if o.captured_at_ms - s.captured_at_ms <= 5_000]
        if (len(recent) >= 3 and recent[-1].captured_at_ms - recent[0].captured_at_ms >= 2_000
                and o.captured_at_ms - recent[-1].captured_at_ms <= 1_000
                and max(s.speed_kmh for s in recent) - min(s.speed_kmh for s in recent) <= 5):
            result.append("steady_speed")
        tracks = sorted((t for t in state.tracks.values()
                         if o.captured_at_ms - t.first_at_ms <= self.sequence_window_ms),
                        key=lambda t: t.first_at_ms)
        # A class change on one physical track is uncertainty, not a second sign.
        if (len(tracks) >= 3 and all(len(t.values) == 1 for t in tracks[-3:])
                and tracks[-3].first_at_ms < tracks[-2].first_at_ms < tracks[-1].first_at_ms):
            values = [next(iter(t.values)) for t in tracks[-3:]]
            if values[0] > values[1] > values[2]:
                result.append("descending_distinct_signs")
        if (state.dismissed_at_ms is not None
                and o.captured_at_ms - state.dismissed_at_ms <= self.sequence_window_ms):
            result.append("dismissed_in_encounter")
        else:
            state.dismissed_at_ms = None
        return tuple(result)
