package de.youspeed.android.alpha

import java.util.Locale

/** Localized messages shared by controller defaults, background callbacks and camera status. */
internal enum class ConsumerRuntimeText(
    private val en: String,
    private val de: String,
    private val fr: String,
    private val nl: String,
) {
    STREET_UNKNOWN(
        "Street unknown",
        "Straße unbekannt",
        "Rue inconnue",
        "Straat onbekend",
    ),
    STARTUP_PREPARING(
        "Preparing local data",
        "Lokale Daten werden vorbereitet",
        "Préparation des données locales",
        "Lokale gegevens voorbereiden",
    ),
    FIRST_LOCATION_WAITING(
        "Map selection is waiting for the first GPS location.",
        "Datenbankauswahl wartet auf den ersten GPS-Standort.",
        "La sélection de carte attend la première position GPS.",
        "Kaartselectie wacht op de eerste GPS-locatie.",
    ),
    MODEL_COUNTRY_PENDING(
        "Traffic sign model: country not yet determined.",
        "Verkehrszeichen-Modell: Land noch nicht bestimmt.",
        "Modèle de panneaux : pays non encore déterminé.",
        "Verkeersbordmodel: land nog niet bepaald.",
    ),
    SPEECH_MODEL_PREPARING(
        "Preparing the included German offline speech model.",
        "Mitgeliefertes deutsches Offline-Sprachmodell wird vorbereitet.",
        "Préparation du modèle vocal allemand hors ligne intégré.",
        "Het meegeleverde Duitse offline spraakmodel wordt voorbereid.",
    ),
    CAMERA_DISABLED(
        "Camera recognition is off.",
        "Kamera-Erkennung ist ausgeschaltet.",
        "La reconnaissance par caméra est désactivée.",
        "Cameraherkenning is uitgeschakeld.",
    ),
    STARTUP_SEED_READY(
        "Karlsruhe starter data and offline speech recognition are ready",
        "Karlsruhe-Basisdaten und Offline-Spracherkennung sind bereit",
        "Les données initiales de Karlsruhe et la reconnaissance vocale hors ligne sont prêtes",
        "Startgegevens van Karlsruhe en offline spraakherkenning zijn gereed",
    ),
    STARTUP_READY(
        "Local data and offline speech recognition are ready",
        "Lokale Daten und Offline-Spracherkennung sind bereit",
        "Les données locales et la reconnaissance vocale hors ligne sont prêtes",
        "Lokale gegevens en offline spraakherkenning zijn gereed",
    ),
    STARTUP_NO_MAP(
        "No local map bundle is active",
        "Noch kein lokales Datenbankpaket aktiv",
        "Aucun paquet de cartes local actif",
        "Geen lokale kaartbundel actief",
    ),
    SPEECH_MODEL_PREPARING_SHORT(
        "Preparing the German offline speech model",
        "Deutsches Offline-Sprachmodell wird vorbereitet",
        "Préparation du modèle vocal allemand hors ligne",
        "Duits offline spraakmodel voorbereiden",
    ),
    STARTUP_FAILED(
        "Could not prepare local data",
        "Lokale Daten konnten nicht vorbereitet werden",
        "Impossible de préparer les données locales",
        "Lokale gegevens konden niet worden voorbereid",
    ),
    FIRST_MAP_COMPLETE(
        "Initial map setup is complete.",
        "Erste Datenbankeinrichtung abgeschlossen.",
        "La configuration initiale de la carte est terminée.",
        "De eerste kaartinstelling is voltooid.",
    ),
    REGION_CATALOG_MISSING(
        "The region catalog is missing or invalid. Select a map manually.",
        "Regionenkatalog fehlt oder ist ungültig. Datenbank bitte manuell auswählen.",
        "Le catalogue des régions est absent ou invalide. Sélectionnez une carte manuellement.",
        "De regiocatalogus ontbreekt of is ongeldig. Kies handmatig een kaart.",
    ),
    MODEL_PREFIX(
        "Traffic sign model: ",
        "Verkehrszeichen-Modell: ",
        "Modèle de panneaux : ",
        "Verkeersbordmodel: ",
    ),
    MODEL_COUNTRY_UNCLEAR(
        "Country is still uncertain near the border.",
        "Land im Grenzbereich noch unklar.",
        "Le pays reste incertain près de la frontière.",
        "Het land is bij de grens nog niet duidelijk.",
    ),
    MODEL_DOWNLOAD_UNAVAILABLE(
        "No approved download package is available yet.",
        "Noch kein freigegebenes Download-Paket verfügbar.",
        "Aucun paquet approuvé n’est encore disponible au téléchargement.",
        "Er is nog geen goedgekeurd downloadpakket beschikbaar.",
    ),
    LOCATION_MAP_UNAVAILABLE(
        "No matching map is available in the catalog for this location.",
        "Für diesen Standort ist keine passende Datenbank im Katalog verfügbar.",
        "Aucune carte adaptée à cette position n’est disponible dans le catalogue.",
        "Er is geen passende kaart voor deze locatie in de catalogus beschikbaar.",
    ),
    REGION_DOWNLOAD_UNAVAILABLE(
        "No download source is available for the matching region.",
        "Kein Download-Endpunkt für die passende Region verfügbar.",
        "Aucune source de téléchargement n’est disponible pour la région correspondante.",
        "Geen downloadbron beschikbaar voor de passende regio.",
    ),
    KEEP_EXISTING_MAPS(
        "Existing maps remain selected.",
        "Vorhandene Datenbanken bleiben ausgewählt.",
        "Les cartes existantes restent sélectionnées.",
        "Bestaande kaarten blijven geselecteerd.",
    ),
    LOCATION_REQUIRED_FOR_MAP(
        "Location permission is required for automatic map selection.",
        "Für die automatische Datenbankauswahl ist die Standortfreigabe erforderlich.",
        "L’autorisation de localisation est nécessaire pour sélectionner automatiquement une carte.",
        "Locatietoestemming is vereist voor automatische kaartselectie.",
    ),
    LOCATION_DENIED(
        "Location permission was not granted.",
        "Standortberechtigung wurde nicht erteilt.",
        "L’autorisation de localisation n’a pas été accordée.",
        "Locatietoestemming is niet verleend.",
    ),
    SCREENSHOT_SPEECH_DISABLED(
        "Speech recognition is disabled in screenshot mode.",
        "Spracherkennung ist im Screenshot-Modus deaktiviert.",
        "La reconnaissance vocale est désactivée en mode capture d’écran.",
        "Spraakherkenning is uitgeschakeld in de schermafbeeldingsmodus.",
    ),
    SPEECH_MODEL_NOT_READY(
        "The included German offline speech model is not ready.",
        "Das mitgelieferte deutsche Offline-Sprachmodell ist nicht bereit.",
        "Le modèle vocal allemand hors ligne intégré n’est pas prêt.",
        "Het meegeleverde Duitse offline spraakmodel is niet gereed.",
    ),
    MIC_PERMISSION_REQUESTED(
        "Requesting microphone permission.",
        "Mikrofonberechtigung wird angefragt.",
        "Demande d’autorisation du microphone.",
        "Microfoontoestemming wordt gevraagd.",
    ),
    MIC_PERMISSION_DENIED(
        "Microphone permission was not granted.",
        "Mikrofonberechtigung wurde nicht erteilt.",
        "L’autorisation du microphone n’a pas été accordée.",
        "Microfoontoestemming is niet verleend.",
    ),
    CAMERA_PERMISSION_DENIED(
        "Camera permission was not granted.",
        "Kameraberechtigung wurde nicht erteilt.",
        "L’autorisation de la caméra n’a pas été accordée.",
        "Cameratoestemming is niet verleend.",
    ),
    CAMERA_PERMISSION_REQUESTED(
        "Requesting camera permission.",
        "Kameraberechtigung wird angefragt.",
        "Demande d’autorisation de la caméra.",
        "Cameratoestemming wordt gevraagd.",
    ),
    GERMANY_ENDPOINTS_MISSING(
        "No Germany download sources found in BundleTargets.top10.json.",
        "Keine Deutschland-Downloadquellen in BundleTargets.top10.json gefunden.",
        "Aucune source de téléchargement pour l’Allemagne dans BundleTargets.top10.json.",
        "Geen Duitse downloadbronnen gevonden in BundleTargets.top10.json.",
    ),
    LOADING_MANIFEST(
        "Loading manifest",
        "Lade Manifest",
        "Chargement du manifeste",
        "Manifest laden",
    ),
    ENDPOINTS_MISSING(
        "No manifest sources configured.",
        "Keine Manifest-Quellen konfiguriert.",
        "Aucune source de manifeste configurée.",
        "Geen manifestbronnen ingesteld.",
    ),
    SYNC_ALREADY_RUNNING(
        "A sync is already running.",
        "Es läuft bereits eine Synchronisierung.",
        "Une synchronisation est déjà en cours.",
        "Er loopt al een synchronisatie.",
    ),
    SYNC_STARTING(
        "Starting sync",
        "Synchronisierung startet",
        "Démarrage de la synchronisation",
        "Synchronisatie starten",
    ),
    SYNC_COMPLETE(
        "Sync complete",
        "Synchronisierung abgeschlossen",
        "Synchronisation terminée",
        "Synchronisatie voltooid",
    ),
    NO_ENDPOINT_SYNCED(
        "Could not sync any manifest source.",
        "Keine Manifest-Quelle konnte synchronisiert werden.",
        "Aucune source de manifeste n’a pu être synchronisée.",
        "Geen manifestbron kon worden gesynchroniseerd.",
    ),
    NO_DOWNLOADED_MAPS(
        "No downloaded maps found.",
        "Keine heruntergeladenen Datenbanken gefunden.",
        "Aucune carte téléchargée trouvée.",
        "Geen gedownloade kaarten gevonden.",
    ),
    DOWNLOAD_BUSY(
        "Download blocked: a sync is already running.",
        "Download blockiert: Es läuft bereits eine Synchronisierung.",
        "Téléchargement bloqué : une synchronisation est déjà en cours.",
        "Download geblokkeerd: er loopt al een synchronisatie.",
    ),
    MAP_DOWNLOAD_FAILED(
        "Map download failed. Retry or select a map.",
        "Datenbank-Download fehlgeschlagen. Erneut versuchen oder eine Datenbank auswählen.",
        "Échec du téléchargement de la carte. Réessayez ou sélectionnez une carte.",
        "Kaartdownload mislukt. Probeer opnieuw of kies een kaart.",
    ),
    OBSERVATION_DELETED(
        "Observation deleted.",
        "Eintrag gelöscht.",
        "Observation supprimée.",
        "Waarneming verwijderd.",
    ),
    NO_OBSERVATIONS(
        "No local observations.",
        "Keine lokalen Erfassungen vorhanden.",
        "Aucune observation locale.",
        "Geen lokale waarnemingen.",
    ),
    OBSERVATION_APPROVED(
        "Observation approved for export.",
        "Beobachtung für den Export freigegeben.",
        "Observation approuvée pour l’export.",
        "Waarneming goedgekeurd voor export.",
    ),
    OBSERVATION_DISCARDED(
        "Observation discarded.",
        "Beobachtung verworfen.",
        "Observation rejetée.",
        "Waarneming verworpen.",
    ),
    GPS_LOG_MISSING(
        "No GPS log file yet.",
        "Noch keine GPS-Protokolldatei vorhanden.",
        "Aucun journal GPS pour le moment.",
        "Nog geen GPS-logbestand.",
    ),
    MATCH_LOG_MISSING(
        "No map-matching log file yet.",
        "Noch kein Zuordnungsprotokoll vorhanden.",
        "Aucun journal de correspondance routière pour le moment.",
        "Nog geen logbestand voor wegkoppeling.",
    ),
    DIAGNOSTIC_LOG_MISSING(
        "No diagnostic log file yet.",
        "Noch kein Diagnoseprotokoll vorhanden.",
        "Aucun journal de diagnostic pour le moment.",
        "Nog geen diagnostisch logbestand.",
    ),
    DRIVING_LOG_CLEARED(
        "Driving log cleared.",
        "Fahrprotokoll geleert.",
        "Journal de trajet vidé.",
        "Rijlogboek gewist.",
    ),
    DIAGNOSTIC_LOG_CLEARED(
        "Diagnostic log cleared.",
        "Diagnoseprotokoll geleert.",
        "Journal de diagnostic vidé.",
        "Diagnostisch logboek gewist.",
    ),
    OSM_LOCATION_MISSING(
        "No OSM location available.",
        "Keine OSM-Position verfügbar.",
        "Aucune position OSM disponible.",
        "Geen OSM-locatie beschikbaar.",
    ),
    SYNC_NOT_STARTED(
        "Not synced",
        "Nicht synchronisiert",
        "Non synchronisé",
        "Niet gesynchroniseerd",
    ),
    SYNC_RUNNING(
        "Syncing…",
        "Synchronisierung…",
        "Synchronisation…",
        "Synchroniseren…",
    ),
    PREPARING(
        "Preparing…",
        "Vorbereitung…",
        "Préparation…",
        "Voorbereiden…",
    ),
    SYNC_FAILED(
        "Sync failed",
        "Synchronisierung fehlgeschlagen",
        "Échec de la synchronisation",
        "Synchronisatie mislukt",
    ),
    STARTER_ACTIVE(
        "Starter data active",
        "Basisdaten aktiv",
        "Données initiales actives",
        "Startgegevens actief",
    ),
    DOWNLOADED(
        "downloaded",
        "geladen",
        "téléchargé",
        "gedownload",
    ),
    SCREENSHOT_READY(
        "Screenshot fixture loaded",
        "Screenshot-Vorlage geladen",
        "Scénario de capture d’écran chargé",
        "Schermafbeeldingsscenario geladen",
    ),
    SCREENSHOT_NO_AUDIO(
        "Screenshot mode does not use live audio.",
        "Screenshot-Modus verwendet kein Live-Audio.",
        "Le mode capture d’écran n’utilise pas l’audio en direct.",
        "De schermafbeeldingsmodus gebruikt geen liveaudio.",
    ),
    LOCATION_PROVIDERS_MISSING(
        "No active location providers available.",
        "Keine aktiven Standortanbieter verfügbar.",
        "Aucun fournisseur de localisation actif disponible.",
        "Geen actieve locatieaanbieders beschikbaar.",
    ),
    LOCATION_UPDATES_FAILED(
        "Could not start location updates.",
        "Standortupdates konnten nicht gestartet werden.",
        "Impossible de démarrer les mises à jour de position.",
        "Locatie-updates konden niet worden gestart.",
    ),
    DRIVING_BAN_ONE(
        "Warning. A one-month driving ban is possible.",
        "Achtung. Ein Monat Fahrverbot möglich.",
        "Attention. Une interdiction de conduire d’un mois est possible.",
        "Let op. Een rijverbod van één maand is mogelijk.",
    ),
    SPEECH_PREPARING(
        "Preparing offline speech recognition.",
        "Offline-Spracherkennung wird vorbereitet.",
        "Préparation de la reconnaissance vocale hors ligne.",
        "Offline spraakherkenning wordt voorbereid.",
    ),
    SPEECH_NOT_READY(
        "The included offline speech model is not ready yet.",
        "Das mitgelieferte Offline-Sprachmodell ist noch nicht bereit.",
        "Le modèle vocal hors ligne intégré n’est pas encore prêt.",
        "Het meegeleverde offline spraakmodel is nog niet gereed.",
    ),
    SPEECH_NOT_LOADED(
        "The offline speech model is not loaded.",
        "Offline-Sprachmodell ist nicht geladen.",
        "Le modèle vocal hors ligne n’est pas chargé.",
        "Het offline spraakmodel is niet geladen.",
    ),
    SPEECH_LISTENING(
        "Speak in German: 10 to 130 or “Fußgängerzone”.",
        "Jetzt auf Deutsch sprechen: 10 bis 130 oder Fußgängerzone.",
        "Parlez en allemand : 10 à 130 ou « Fußgängerzone ».",
        "Spreek in het Duits: 10 tot 130 of ‘Fußgängerzone’.",
    ),
    CORRECTION_PROMPT(
        "Correction. Speak in German.",
        "Korrektur. Bitte auf Deutsch sprechen.",
        "Correction. Parlez en allemand.",
        "Correctie. Spreek in het Duits.",
    ),
    SPEECH_ALREADY_ACTIVE(
        "Speech recognition is already active.",
        "Spracherkennung ist bereits aktiv.",
        "La reconnaissance vocale est déjà active.",
        "Spraakherkenning is al actief.",
    ),
    SPEECH_MODEL_READY(
        "The included German offline speech model is ready.",
        "Das mitgelieferte deutsche Offline-Sprachmodell ist bereit.",
        "Le modèle vocal allemand hors ligne intégré est prêt.",
        "Het meegeleverde Duitse offline spraakmodel is gereed.",
    ),
    SPEECH_PREPARATION_FAILED(
        "Could not prepare the German speech model",
        "Deutsches Sprachmodell konnte nicht vorbereitet werden",
        "Impossible de préparer le modèle vocal allemand",
        "Het Duitse spraakmodel kon niet worden voorbereid",
    ),
    MODEL_COUNTRY_PREFIX(
        "Traffic sign model %1\$s: ",
        "Verkehrszeichen-Modell %1\$s: ",
        "Modèle de panneaux %1\$s : ",
        "Verkeersbordmodel %1\$s: ",
    ),
    MATCHING_MAP_LOADING(
        "Downloading the matching map: %1\$s.",
        "Lade die passende Datenbank: %1\$s.",
        "Téléchargement de la carte adaptée : %1\$s.",
        "De passende kaart wordt gedownload: %1\$s.",
    ),
    MANIFEST_LOADED(
        "Manifest loaded: %1\$s",
        "Manifest geladen: %1\$s",
        "Manifeste chargé : %1\$s",
        "Manifest geladen: %1\$s",
    ),
    DOWNLOADING_NAME(
        "Downloading %1\$s",
        "Lade %1\$s",
        "Téléchargement de %1\$s",
        "%1\$s downloaden",
    ),
    MAPS_DELETED(
        "Downloaded maps deleted: %1\$s.",
        "Heruntergeladene Datenbanken gelöscht: %1\$s.",
        "Cartes téléchargées supprimées : %1\$s.",
        "Gedownloade kaarten verwijderd: %1\$s.",
    ),
    MAPS_DELETE_FAILED(
        "Could not delete downloaded maps: %1\$s",
        "Heruntergeladene Datenbanken konnten nicht gelöscht werden: %1\$s",
        "Impossible de supprimer les cartes téléchargées : %1\$s",
        "Gedownloade kaarten konden niet worden verwijderd: %1\$s",
    ),
    DOWNLOAD_STARTED(
        "Download started: %1\$s",
        "Download gestartet: %1\$s",
        "Téléchargement démarré : %1\$s",
        "Download gestart: %1\$s",
    ),
    MATCHING_MAP_READY(
        "Matching map ready offline: %1\$s.",
        "Passende Datenbank ist offline bereit: %1\$s.",
        "Carte adaptée prête hors ligne : %1\$s.",
        "Passende kaart offline gereed: %1\$s.",
    ),
    MAP_LOADED(
        "Map downloaded: %1\$s",
        "Datenbank geladen: %1\$s",
        "Carte téléchargée : %1\$s",
        "Kaart gedownload: %1\$s",
    ),
    MAP_DELETED(
        "Map deleted: %1\$s",
        "Datenbank gelöscht: %1\$s",
        "Carte supprimée : %1\$s",
        "Kaart verwijderd: %1\$s",
    ),
    MAP_NOT_DELETED(
        "No map deleted: %1\$s",
        "Keine Datenbank gelöscht: %1\$s",
        "Aucune carte supprimée : %1\$s",
        "Geen kaart verwijderd: %1\$s",
    ),
    MAP_DELETE_FAILED(
        "Could not delete map: %1\$s",
        "Datenbank konnte nicht gelöscht werden: %1\$s",
        "Impossible de supprimer la carte : %1\$s",
        "Kaart kon niet worden verwijderd: %1\$s",
    ),
    OBSERVATION_SAVED(
        "Recorded: OSM way %1\$s, old %2\$s, new %3\$s.",
        "Erfasst: OSM-Weg %1\$s, alt %2\$s, neu %3\$s.",
        "Enregistré : voie OSM %1\$s, ancienne %2\$s, nouvelle %3\$s.",
        "Vastgelegd: OSM-weg %1\$s, oud %2\$s, nieuw %3\$s.",
    ),
    OBSERVATION_SAVE_FAILED(
        "Could not save local observation: %1\$s",
        "Lokale Erfassung konnte nicht gespeichert werden: %1\$s",
        "Impossible d’enregistrer l’observation locale : %1\$s",
        "Lokale waarneming kon niet worden opgeslagen: %1\$s",
    ),
    DELETE_FAILED(
        "Deletion failed: %1\$s",
        "Löschen fehlgeschlagen: %1\$s",
        "Échec de la suppression : %1\$s",
        "Verwijderen mislukt: %1\$s",
    ),
    OBSERVATIONS_DELETED(
        "Local observations deleted: %1\$s.",
        "Lokale Erfassungen gelöscht: %1\$s.",
        "Observations locales supprimées : %1\$s.",
        "Lokale waarnemingen verwijderd: %1\$s.",
    ),
    DELETE_ALL_FAILED(
        "Could not delete all observations: %1\$s",
        "Alle Einträge löschen fehlgeschlagen: %1\$s",
        "Impossible de supprimer toutes les observations : %1\$s",
        "Niet alle waarnemingen konden worden verwijderd: %1\$s",
    ),
    EXPORT_CREATED_COUNT(
        "Export created (%1\$s OSM ways): changes.osc",
        "Export erstellt (%1\$s OSM-Wege): changes.osc",
        "Export créé (%1\$s voies OSM) : changes.osc",
        "Export gemaakt (%1\$s OSM-wegen): changes.osc",
    ),
    EXPORT_FAILED(
        "Export failed: %1\$s",
        "Export fehlgeschlagen: %1\$s",
        "Échec de l’export : %1\$s",
        "Export mislukt: %1\$s",
    ),
    APPROVAL_FAILED(
        "Approval failed: %1\$s",
        "Freigabe fehlgeschlagen: %1\$s",
        "Échec de l’approbation : %1\$s",
        "Goedkeuren mislukt: %1\$s",
    ),
    DISCARD_FAILED(
        "Discard failed: %1\$s",
        "Verwerfen fehlgeschlagen: %1\$s",
        "Échec du rejet : %1\$s",
        "Verwerpen mislukt: %1\$s",
    ),
    EXPORT_CREATED(
        "Export created: %1\$s",
        "Export erstellt: %1\$s",
        "Export créé : %1\$s",
        "Export gemaakt: %1\$s",
    ),
    SINGLE_EXPORT_FAILED(
        "Observation export failed: %1\$s",
        "Einzelexport fehlgeschlagen: %1\$s",
        "Échec de l’export de l’observation : %1\$s",
        "Export van waarneming mislukt: %1\$s",
    ),
    CLEAR_DRIVING_LOG_FAILED(
        "Could not clear driving log: %1\$s",
        "Fahrprotokoll leeren fehlgeschlagen: %1\$s",
        "Impossible de vider le journal de trajet : %1\$s",
        "Rijlogboek kon niet worden gewist: %1\$s",
    ),
    CLEAR_DIAGNOSTIC_LOG_FAILED(
        "Could not clear diagnostic log: %1\$s",
        "Diagnoseprotokoll leeren fehlgeschlagen: %1\$s",
        "Impossible de vider le journal de diagnostic : %1\$s",
        "Diagnostisch logboek kon niet worden gewist: %1\$s",
    ),
    DOWNLOADED_VERSION(
        "downloaded (%1\$s)",
        "geladen (%1\$s)",
        "téléchargé (%1\$s)",
        "gedownload (%1\$s)",
    ),
    DRIVING_BAN_MONTHS(
        "Warning. A driving ban of %1\$s months is possible.",
        "Achtung. %1\$s Monate Fahrverbot möglich.",
        "Attention. Une interdiction de conduire de %1\$s mois est possible.",
        "Let op. Een rijverbod van %1\$s maanden is mogelijk.",
    ),
    SPEECH_INIT_FAILED(
        "Could not initialize offline speech recognition: %1\$s",
        "Offline-Spracherkennung konnte nicht initialisiert werden: %1\$s",
        "Impossible d’initialiser la reconnaissance vocale hors ligne : %1\$s",
        "Offline spraakherkenning kon niet worden gestart: %1\$s",
    ),
    SPEECH_FAILED(
        "Offline speech recognition failed: %1\$s",
        "Offline-Spracherkennung fehlgeschlagen: %1\$s",
        "Échec de la reconnaissance vocale hors ligne : %1\$s",
        "Offline spraakherkenning mislukt: %1\$s",
    ),
    SPEECH_START_FAILED(
        "Could not start speech recognition: %1\$s",
        "Spracherkennung konnte nicht gestartet werden: %1\$s",
        "Impossible de démarrer la reconnaissance vocale : %1\$s",
        "Spraakherkenning kon niet worden gestart: %1\$s",
    ),
    SPEECH_MODEL_PREPARATION_FAILED(
        "Could not prepare the included offline speech model: %1\$s",
        "Das mitgelieferte Offline-Sprachmodell konnte nicht vorbereitet werden: %1\$s",
        "Impossible de préparer le modèle vocal hors ligne intégré : %1\$s",
        "Het meegeleverde offline spraakmodel kon niet worden voorbereid: %1\$s",
    ),
    DOWNLOAD_PREPARING(
        "Preparing map download",
        "Datenbank-Download wird vorbereitet",
        "Préparation du téléchargement de la carte",
        "Kaartdownload voorbereiden",
    ),
    DOWNLOAD_RUNNING(
        "Downloading map data",
        "Datenbank wird geladen",
        "Téléchargement des données cartographiques",
        "Kaartgegevens downloaden",
    ),
    DOWNLOAD_ASSEMBLING(
        "Preparing downloaded map data",
        "Heruntergeladene Datenbank wird vorbereitet",
        "Préparation des données cartographiques téléchargées",
        "Gedownloade kaartgegevens voorbereiden",
    ),
    SYNC_CURRENT(
        "Map data is up to date",
        "Datenbank ist aktuell",
        "Les cartes sont à jour",
        "Kaartgegevens zijn actueel",
    ),
    MANIFEST_READY(
        "Manifest ready",
        "Manifest bereit",
        "Manifeste prêt",
        "Manifest gereed",
    ),
    CAMERA_MODEL_LOADING(
        "Verifying and loading the camera recognition model.",
        "Kameramodell wird geprüft und geladen.",
        "Vérification et chargement du modèle de reconnaissance par caméra.",
        "Cameraherkenningsmodel controleren en laden.",
    ),
    REAR_CAMERA_UNAVAILABLE(
        "Rear camera is unavailable.",
        "Rückkamera ist nicht verfügbar.",
        "La caméra arrière n’est pas disponible.",
        "Achtercamera is niet beschikbaar.",
    ),
    CAMERA_ACTIVE(
        "Camera recognition is active.",
        "Kamera-Erkennung ist aktiv.",
        "La reconnaissance par caméra est active.",
        "Cameraherkenning is actief.",
    ),
    PEDESTRIAN_ZONE(
        "Pedestrian zone",
        "Fußgängerzone",
        "Zone piétonne",
        "Voetgangerszone",
    ),
    COORDINATES(
        "Coordinates",
        "Koordinate",
        "Coordonnées",
        "Coördinaten",
    ),
    SPEED(
        "Speed",
        "Geschwindigkeit",
        "Vitesse",
        "Snelheid",
    ),
    SPEED_LIMIT(
        "Speed limit",
        "Tempolimit",
        "Limitation de vitesse",
        "Snelheidslimiet",
    ),
    UNLIMITED(
        "unlimited",
        "unbegrenzt",
        "illimitée",
        "onbeperkt",
    ),
    OVERSPEED(
        "Overspeed",
        "Überschreitung",
        "Dépassement",
        "Overschrijding",
    ),
    DRIVE_STATUS(
        "Driving status",
        "Fahrstatus",
        "État de conduite",
        "Rijstatus",
    ),
    GPS_FIXES(
        "GPS fixes",
        "GPS-Positionen",
        "Positions GPS",
        "GPS-posities",
    ),
    ACTIVE_BUNDLE(
        "Active map bundle",
        "Aktives Datenbankpaket",
        "Paquet de cartes actif",
        "Actieve kaartbundel",
    ),
    ACTIVE_DATABASE(
        "Active database",
        "Aktive Datenbank",
        "Base de données active",
        "Actieve database",
    ),
    DATABASE_PATH(
        "Database path",
        "Datenbankpfad",
        "Chemin de la base",
        "Databasepad",
    ),
    WAY_ID(
        "OSM way ID",
        "OSM-Weg-ID",
        "Identifiant de voie OSM",
        "OSM-weg-ID",
    ),
    STREET(
        "Street",
        "Straße",
        "Rue",
        "Straat",
    ),
    CITY(
        "City",
        "Stadt",
        "Ville",
        "Plaats",
    ),
    LOCALITY(
        "Locality",
        "Ort",
        "Localité",
        "Plaatsnaam",
    ),
    DISTRICT(
        "District",
        "Kreis",
        "Arrondissement",
        "District",
    ),
    GPS_SIGNAL(
        "GPS signal",
        "GPS-Signal",
        "Signal GPS",
        "GPS-signaal",
    ),
    GPS_ACCURACY(
        "GPS accuracy",
        "GPS-Genauigkeit",
        "Précision GPS",
        "GPS-nauwkeurigheid",
    ),
    MATCHER(
        "Map matching",
        "Straßenzuordnung",
        "Correspondance routière",
        "Wegkoppeling",
    ),
    TUNNEL_MODE(
        "Tunnel mode",
        "Tunnelmodus",
        "Mode tunnel",
        "Tunnelmodus",
    ),
    BUILT_UP_AREA(
        "Built-up area",
        "Innerorts",
        "En agglomération",
        "Binnen bebouwde kom",
    ),
    YES(
        "yes",
        "ja",
        "oui",
        "ja",
    ),
    NO(
        "no",
        "nein",
        "non",
        "nee",
    ),
    QUERY_TIME(
        "Query time",
        "Abfragezeit",
        "Durée de la requête",
        "Zoektijd",
    ),
    CANDIDATES(
        "Candidates",
        "Kandidaten",
        "Candidats",
        "Kandidaten",
    ),
    WITH_LIMIT(
        "With speed limit",
        "Mit Tempolimit",
        "Avec limitation",
        "Met snelheidslimiet",
    ),
    NEAREST_ROAD(
        "Nearest road",
        "Nächste Straße",
        "Route la plus proche",
        "Dichtstbijzijnde weg",
    ),
    NEAREST_LIMIT(
        "Nearest speed limit",
        "Nächstes Tempolimit",
        "Limitation la plus proche",
        "Dichtstbijzijnde snelheidslimiet",
    ),
    CITY_SOURCE(
        "City source",
        "Stadtquelle",
        "Source de la ville",
        "Plaatsbron",
    ),
    GPS_LOG(
        "GPS log",
        "GPS-Protokoll",
        "Journal GPS",
        "GPS-logboek",
    ),
    MATCH_LOG(
        "Map-matching log",
        "Zuordnungsprotokoll",
        "Journal routier",
        "Logboek wegkoppeling",
    ),
    DIAGNOSTIC_LOG(
        "Diagnostic log",
        "Diagnoseprotokoll",
        "Journal de diagnostic",
        "Diagnostisch logboek",
    ),
    LOOKUP(
        "Lookup",
        "Abfrage",
        "Recherche",
        "Opzoeken",
    ),
    MANIFEST_SOURCES(
        "Manifest sources",
        "Manifest-Quellen",
        "Sources de manifestes",
        "Manifestbronnen",
    ),
    MANIFEST_COUNTRIES(
        "Manifest countries",
        "Manifest-Länder",
        "Pays des manifestes",
        "Manifestlanden",
    ),
    ACTIVE(
        "active",
        "aktiv",
        "actif",
        "actief",
    ),
    INACTIVE(
        "inactive",
        "inaktiv",
        "inactif",
        "inactief",
    ),
    DRIVING_STOPPED(
        "stopped",
        "gestoppt",
        "arrêté",
        "gestopt",
    ),
    DRIVING_RUNNING(
        "running",
        "aktiv",
        "actif",
        "actief",
    );

    fun text(vararg arguments: Any, locale: Locale = Locale.getDefault()): String {
        val template = ConsumerUiStrings.text(en, de, fr, nl, locale)
        return if (arguments.isEmpty()) template else String.format(locale, template, *arguments)
    }
}
